# Generated by Django 5.0.1 on 2024-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.CharField(default='Available', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='make_year',
            field=models.IntegerField(default=2024),
        ),
    ]
